name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Джоба для линтеров и безопасности (быстрая)
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run pre-commit
        run: uv run pre-commit run --all-files

  # 2. Джоба для тестов (может идти дольше)
  test:
    runs-on: ubuntu-latest
    # Запускать тесты, только если линтеры прошли (опционально)
    # needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run pytest
        run: uv run pytest -v --cov=src
